from enum import Enum


class SimulationEvents(Enum):
    HANDOVER = "HANDOVER"
    HANDOVER_TYPE_DETECTION = "HANDOVER_TYPE_DETECTION"


class HandoverEventTypes(Enum):
    HANDOVER_SUCCESS = "HANDOVER_SUCCESS"
    HANDOVER_TOO_EARLY = "HANDOVER_TOO_EARLY"
    HANDOVER_TOO_LATE = "HANDOVER_TOO_LATE"
    HANDOVER_PING_PONG = "HANDOVER_PING_PONG"
