"""
REINFORCE policy gradient agent for handover optimization.

Implements: Monte Carlo policy gradient with entropy bonus and baseline subtraction.
State representation: Continuous (no binning), normalized to [-1, 1] range.
Policy: Small neural network parameterizing stochastic policy π(action|state).
"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.distributions import Categorical
from typing import Tuple

from entities.network import Network
from entities.ue import UE


class PolicyNetwork(nn.Module):
    """
    Small MLP policy network: state (5D) → action logits (2D).
    
    Architecture:
    - 5 → 32 → 32 → 2 (shallow to avoid overfitting on ~36 effective states)
    - Tanh activations (better for normalized inputs than ReLU)
    - Output: Raw logits → Categorical distribution
    """

    def __init__(self, state_dim: int = 5, hidden_dim: int = 32):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 2)  # Binary action space: stay (0), handover (1)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Batch of states, shape (batch_size, 5)
            
        Returns:
            Action logits, shape (batch_size, 2)
        """
        return self.net(x)

    def action_probabilities(self, x: torch.Tensor) -> Categorical:
        """
        Get action distribution for a state batch.
        
        Args:
            x: State tensor, shape (batch_size, 5)
            
        Returns:
            Categorical distribution over actions
        """
        logits = self.forward(x)
        return Categorical(logits=logits)


class REINFORCEAgent:
    """
    REINFORCE (Monte Carlo Policy Gradient) Agent.
    
    Key features:
    - On-policy: only learns from trajectories generated by current policy
    - Episodic: single gradient update per episode over full trajectory
    - Baseline subtraction: reduces variance without introducing bias
    - Entropy bonus: prevents premature policy collapse in sparse reward settings
    """

    def __init__(
        self,
        state_dim: int = 5,
        hidden_dim: int = 32,
        lr: float = 3e-4,
        gamma: float = 0.97,
        baseline: bool = True,
        entropy_coef: float = 0.01,
    ):
        """
        Initialize REINFORCE agent.
        
        Args:
            state_dim: Dimension of state vector (5 for this task)
            hidden_dim: Hidden layer size in policy network (32 recommended)
            lr: Adam learning rate (3e-4 good for small networks)
            gamma: Discount factor (match Q-Learning at 0.97 for fair comparison)
            baseline: Whether to subtract mean return (reduces variance)
            entropy_coef: Weight of entropy bonus term (0.01 prevents collapse)
        """
        self.gamma = gamma
        self.baseline = baseline
        self.entropy_coef = entropy_coef

        self.policy = PolicyNetwork(state_dim, hidden_dim)
        self.optimizer = optim.Adam(self.policy.parameters(), lr=lr)

        # Episode trajectory buffers (cleared per episode)
        self._log_probs: list[torch.Tensor] = []
        self._rewards: list[float] = []
        self._entropies: list[torch.Tensor] = []

    def select_action(self, state: np.ndarray) -> Tuple[int, torch.Tensor, torch.Tensor]:
        """
        Select action and return components needed for update.
        Called every step during episode.
        
        Args:
            state: Continuous state vector, shape (5,)
            
        Returns:
            Tuple of (action_idx, log_prob, entropy)
        """
        x = torch.FloatTensor(state).unsqueeze(0)  # Add batch dimension
        dist = self.policy.action_probabilities(x)
        action = dist.sample()
        log_prob = dist.log_prob(action)
        entropy = dist.entropy()

        return action.item(), log_prob, entropy

    def store_transition(
        self,
        log_prob: torch.Tensor,
        reward: float,
        entropy: torch.Tensor
    ):
        """
        Store (log_prob, reward, entropy) in episode buffer.
        Called every step during episode.
        
        Args:
            log_prob: Log probability of selected action
            reward: Immediate reward signal
            entropy: Entropy of action distribution (for bonus term)
        """
        self._log_probs.append(log_prob)
        self._rewards.append(reward)
        self._entropies.append(entropy)

    def update(self) -> float:
        """
        Perform REINFORCE update over full episode trajectory.
        Called once per episode.
        
        Procedure:
        1. Compute discounted returns G_t for each timestep
        2. Normalize returns to reduce variance (baseline subtraction)
        3. Compute policy gradient: -E[G_t * log π(a_t|s_t)]
        4. Add entropy bonus: encourages exploration
        5. Backward pass with gradient clipping
        
        Returns:
            Loss value for logging
        """
        if not self._log_probs:
            return 0.0

        # 1. Compute discounted returns G_t (backward from episode end)
        returns = []
        G = 0.0
        for r in reversed(self._rewards):
            G = r + self.gamma * G
            returns.insert(0, G)

        returns = torch.FloatTensor(returns)

        # 2. Baseline: normalize returns to zero mean, unit std
        if self.baseline:
            returns = (returns - returns.mean()) / (returns.std() + 1e-8)

        # 3. Policy gradient loss: -E[G_t * log π(a_t|s_t)]
        log_probs = torch.stack(self._log_probs)
        entropies = torch.stack(self._entropies)

        policy_loss = -(log_probs * returns).mean()

        # 4. Entropy bonus: -coef * mean(entropy) encourages exploration
        entropy_loss = -self.entropy_coef * entropies.mean()

        loss = policy_loss + entropy_loss

        # 5. Gradient step with clipping
        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.policy.parameters(), max_norm=0.5)
        self.optimizer.step()

        # Clear buffers for next episode
        self._log_probs.clear()
        self._rewards.clear()
        self._entropies.clear()

        return loss.item()

    def save(self, path: str):
        """Save policy network and optimizer state."""
        torch.save({
            'policy_state': self.policy.state_dict(),
            'optimizer_state': self.optimizer.state_dict(),
        }, path)

    def load(self, path: str):
        """Load policy network and optimizer state."""
        checkpoint = torch.load(path, weights_only=True)
        self.policy.load_state_dict(checkpoint['policy_state'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state'])
